import type { Reel } from '../ai/schema.js';
import type { Locale } from '../i18n.js';

/** The example shown on the landing page, rendered with the same component as real results. */
export const SAMPLE_REEL: Record<Locale, Reel> = {
  ru: {
    title: 'Почему дешёвые услуги продаются хуже',
    hook_type: 'expectation_gap',
    blocks: [
      {
        kind: 'hook',
        start_sec: 0,
        end_sec: 3,
        voice: 'Вы снижаете цену — и теряете клиентов.',
        on_screen_text: 'Дешевле — значит меньше заказов',
        visual: 'Крупный план, резкий зум на «теряете»',
        source_timecode: '14:02–14:05',
      },
      {
        kind: 'promise',
        start_sec: 3,
        end_sec: 7,
        voice: 'Покажу, почему так происходит и что делать вместо скидок.',
        on_screen_text: 'Что делать вместо скидок',
        visual: 'Средний план, текст по центру',
        source_timecode: null,
      },
      {
        kind: 'body',
        start_sec: 7,
        end_sec: 18,
        voice: 'Мы подняли цену в два раза — и заявок стало больше на треть.',
        on_screen_text: 'Цена ×2 → заявок +30%',
        visual: 'Смена ракурса, график на экране',
        source_timecode: '14:20–14:31',
      },
      {
        kind: 'body',
        start_sec: 18,
        end_sec: 29,
        voice: 'Клиент не может оценить качество заранее. Цена — единственный сигнал, который он видит.',
        on_screen_text: 'Цена = сигнал качества',
        visual: 'Крупный план, субтитры по 3 слова',
        source_timecode: '15:02–15:12',
      },
      {
        kind: 'payoff',
        start_sec: 29,
        end_sec: 45,
        voice: 'Не снижайте цену. Снижайте риск клиента: гарантия, сроки, кейсы — и платить станут охотнее.',
        on_screen_text: 'Снижайте риск, а не цену',
        visual: 'Самый чистый кадр, 2 секунды воздуха в конце',
        source_timecode: '18:10–18:26',
      },
      {
        kind: 'cta',
        start_sec: 45,
        end_sec: 52,
        voice: 'Напишите «ЦЕНА» в комментариях — пришлю шаблон гарантии.',
        on_screen_text: 'Напишите «ЦЕНА» 👇',
        visual: 'Спикер в кадр, текст снизу',
        source_timecode: null,
      },
    ],
    alternative_hooks: ['Скидка — самый дорогой способ продавать.', 'Мы подняли цену ×2. Заявок стало больше.'],
    cover_text: 'Почему скидки не продают',
    caption: 'Снизили цену, а заявок стало меньше? Это не случайность.',
    hashtags: ['#фриланс', '#продажи', '#ценообразование'],
    editing_notes: ['Вырезать паузы встык', 'Щелчок на стыке блоков'],
    loop_note: '«…шаблон гарантии» → «Вы снижаете цену»',
  },
  en: {
    title: 'Why cheap services sell worse',
    hook_type: 'expectation_gap',
    blocks: [
      {
        kind: 'hook',
        start_sec: 0,
        end_sec: 3,
        voice: 'You lower your price — and lose clients.',
        on_screen_text: 'Cheaper means fewer orders',
        visual: 'Close-up, punch-in on “lose”',
        source_timecode: '14:02–14:05',
      },
      {
        kind: 'promise',
        start_sec: 3,
        end_sec: 7,
        voice: 'Here’s why it happens and what to do instead of discounts.',
        on_screen_text: 'What to do instead of discounts',
        visual: 'Medium shot, centered text',
        source_timecode: null,
      },
      {
        kind: 'body',
        start_sec: 7,
        end_sec: 18,
        voice: 'We doubled our price — and got a third more leads.',
        on_screen_text: 'Price ×2 → leads +30%',
        visual: 'Angle change, chart on screen',
        source_timecode: '14:20–14:31',
      },
      {
        kind: 'body',
        start_sec: 18,
        end_sec: 29,
        voice: 'Clients can’t judge quality up front. Price is the only signal they see.',
        on_screen_text: 'Price = quality signal',
        visual: 'Close-up, 3-word subtitles',
        source_timecode: '15:02–15:12',
      },
      {
        kind: 'payoff',
        start_sec: 29,
        end_sec: 45,
        voice: 'Don’t cut the price. Cut the client’s risk: guarantees, deadlines, case studies — and they’ll pay gladly.',
        on_screen_text: 'Cut the risk, not the price',
        visual: 'Cleanest shot, 2 seconds of air at the end',
        source_timecode: '18:10–18:26',
      },
      {
        kind: 'cta',
        start_sec: 45,
        end_sec: 52,
        voice: 'Comment “PRICE” and I’ll send you my guarantee template.',
        on_screen_text: 'Comment “PRICE” 👇',
        visual: 'Speaker on camera, text at the bottom',
        source_timecode: null,
      },
    ],
    alternative_hooks: ['Discounts are the most expensive way to sell.', 'We doubled our price. Leads went up.'],
    cover_text: 'Why discounts don’t sell',
    caption: 'Lowered your price and got fewer leads? That’s not a coincidence.',
    hashtags: ['#freelance', '#sales', '#pricing'],
    editing_notes: ['Cut pauses back-to-back', 'Click sound on beat joins'],
    loop_note: '“…guarantee template” → “You lower your price”',
  },
};
